blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/tr3v3r/react-native-esc-pos-printer/discussions/categories/q-a
    about: Please ask and answer questions here.
  - name: Feature request
    url: https://github.com/tr3v3r/react-native-esc-pos-printer/discussions/categories/ideas
    about: Please submit feature requests here.
